import type { SessionWithTape } from './types';

const now = Date.now();
const DAY = 86400000;

const players = [
  { id: 'p1', name: 'Sam', avatar: '🎸', avatarColor: '#6366f1' },
  { id: 'p2', name: 'Alex', avatar: '🎧', avatarColor: '#f59e0b' },
  { id: 'p3', name: 'Jordan', avatar: '🎹', avatarColor: '#10b981' },
  { id: 'p4', name: 'Riley', avatar: '🎤', avatarColor: '#ef4444' },
  { id: 'p5', name: 'Casey', avatar: '🥁', avatarColor: '#8b5cf6' },
  { id: 'p6', name: 'Morgan', avatar: '🎺', avatarColor: '#ec4899' },
];

export const MOCK_SESSIONS: SessionWithTape[] = [
  {
    id: 's1',
    name: 'Friday Night Vinyl',
    description: 'Weekly picks with the crew',
    adminId: 'p1',
    slug: 'mock-session-p1',
    activeTapeIndex: 0,
    ended: false,
    activeTape: {
      id: 't1',
      sessionId: 's1',
      title: 'Magneto, Master of Magnetism',
      prompt: 'polarizing "love it or hate it" songs',
      status: 'submitting',
      deadline: now + 3 * DAY,
    },
    userActionDone: false,
    players,
  },
  {
    id: 's1b',
    name: 'Friday Night Vinyl (submitted)',
    description: 'Weekly picks with the crew',
    adminId: 'p1',
    slug: 'mock-session-p1',
    activeTapeIndex: 0,
    ended: false,
    activeTape: {
      id: 't1b',
      sessionId: 's1b',
      title: 'Magneto, Master of Magnetism',
      prompt: 'polarizing "love it or hate it" songs',
      status: 'submitting',
      deadline: now + 3 * DAY,
    },
    userActionDone: true,
    players,
  },
  {
    id: 's2',
    name: 'Road Trip Jams',
    description: 'Songs for the open road',
    adminId: 'p3',
    slug: 'mock-session-p3',
    activeTapeIndex: 0,
    ended: false,
    activeTape: {
      id: 't2',
      sessionId: 's2',
      title: 'Two-Face aka Harvey Dent',
      prompt: 'songs that start in one style then switch halfway through',
      status: 'playlist_ready',
      deadline: now + 1 * DAY,
    },
    userActionDone: false,
    players: players.slice(0, 4),
  },
  {
    id: 's2b',
    name: 'Road Trip Jams (commented)',
    description: 'Songs for the open road',
    adminId: 'p3',
    slug: 'mock-session-p3',
    activeTapeIndex: 0,
    ended: false,
    activeTape: {
      id: 't2b',
      sessionId: 's2b',
      title: 'Two-Face aka Harvey Dent',
      prompt: 'songs that start in one style then switch halfway through',
      status: 'playlist_ready',
      deadline: now + 1 * DAY,
    },
    userActionDone: true,
    players: players.slice(0, 4),
  },
  {
    id: 's3',
    name: 'Deep Cuts Club',
    description: 'No singles allowed',
    adminId: 'p5',
    slug: 'mock-session-p5',
    activeTapeIndex: 0,
    ended: false,
    activeTape: {
      id: 't3',
      sessionId: 's3',
      title: 'Guilty pleasures',
      prompt: "songs you'd never admit to loving",
      status: 'playlist_ready',
    },
    userActionDone: false,
    players: [players[0], players[3], players[4], players[5]],
  },
  {
    id: 's4',
    name: 'Throwback Thursday',
    description: 'Nostalgia only',
    adminId: 'p2',
    slug: 'mock-session-p2',
    activeTapeIndex: 0,
    ended: false,
    activeTape: {
      id: 't4',
      sessionId: 's4',
      title: 'Spider-Man, Your Friendly Neighborhood Web-Slinger',
      prompt: 'fun, youthful, upbeat bangers',
      status: 'results',
      completedAt: now - 6 * DAY,
    },
    userActionDone: false,
    players: [players[0], players[1], players[2], players[5]],
  },
  {
    id: 's5',
    name: 'Summer 2025 Mix',
    description: 'The soundtrack to last summer',
    adminId: 'p1',
    slug: 'mock-session-ended',
    activeTapeIndex: 0,
    ended: true,
    activeTape: {
      id: 't5',
      sessionId: 's5',
      title: 'Final Round',
      prompt: 'the song of the summer',
      status: 'results',
      completedAt: now - 90 * DAY,
    },
    userActionDone: true,
    players: [players[0], players[1], players[3]],
  },
];
