#!/usr/bin/env node
/**
 * Point .env.local at the Supabase preview branch for the current git branch.
 * Falls back to prod if no preview branch exists (e.g. on main).
 *
 * Usage: npm run env:local
 *
 * Requires SUPABASE_ACCESS_TOKEN env var (personal access token).
 * Set it in your shell profile or pass inline:
 *   SUPABASE_ACCESS_TOKEN=sbp_... npm run env:local
 */

import { execSync } from 'child_process';
import { writeFileSync, readFileSync } from 'fs';

const PROJECT_REF = 'mryuusvhdadbjpupzpol';
const PROD_URL = 'https://mryuusvhdadbjpupzpol.supabase.co';
const PROD_ANON_KEY = 'sb_publishable_7PyRer7MQfOvQHKzlrKhMw_T-iNUTBh';
const VAPID_KEY = 'BE2z5xOQVkgl-GbMsaRi0nFmc8DpocUFkI_Li1vSHZSm-vE7H2EdYwpnQeTmSSSmtqXbCt4-wZC-Lk78US83ryc';

// Try to read access token from env or .env file
let accessToken = process.env.SUPABASE_ACCESS_TOKEN;
if (!accessToken) {
  try {
    const envFile = readFileSync('.env', 'utf8');
    const match = envFile.match(/SUPABASE_ACCESS_TOKEN=(.+)/);
    if (match) accessToken = match[1].trim();
  } catch {}
}

const gitBranch = execSync('git branch --show-current', { encoding: 'utf8' }).trim();
console.log(`Current branch: ${gitBranch}`);

function writeEnv(url, key, label) {
  const content = [
    `# Auto-generated by scripts/env-local.mjs`,
    `# ${label}`,
    `VITE_SUPABASE_URL=${url}`,
    `VITE_SUPABASE_ANON_KEY=${key}`,
    `VITE_VAPID_PUBLIC_KEY=${VAPID_KEY}`,
  ].join('\n') + '\n';
  writeFileSync('.env.local', content);
  console.log(`Wrote .env.local → ${url} (${label})`);
}

if (gitBranch === 'main' || !accessToken) {
  if (!accessToken) console.log('No SUPABASE_ACCESS_TOKEN — defaulting to prod');
  writeEnv(PROD_URL, PROD_ANON_KEY, 'prod');
  process.exit(0);
}

// Look for a preview branch matching the current git branch
console.log(`Looking for preview branch...`);
const res = await fetch(`https://api.supabase.com/v1/projects/${PROJECT_REF}/branches`, {
  headers: { Authorization: `Bearer ${accessToken}` },
});

if (!res.ok) {
  console.log(`Failed to list branches (${res.status}) — defaulting to prod`);
  writeEnv(PROD_URL, PROD_ANON_KEY, 'prod (branch lookup failed)');
  process.exit(0);
}

const branches = await res.json();
const branch = branches.find((b) => b.git_branch === gitBranch);

if (!branch) {
  console.log(`No preview branch for "${gitBranch}" — defaulting to prod`);
  writeEnv(PROD_URL, PROD_ANON_KEY, 'prod (no preview branch)');
  process.exit(0);
}

const branchRef = branch.project_ref;
console.log(`Found preview branch: ${branchRef} (${branch.status})`);

// Get API keys
const keysRes = await fetch(`https://api.supabase.com/v1/projects/${branchRef}/api-keys`, {
  headers: { Authorization: `Bearer ${accessToken}` },
});

if (!keysRes.ok) {
  console.log(`Failed to get API keys (${keysRes.status}) — defaulting to prod`);
  writeEnv(PROD_URL, PROD_ANON_KEY, 'prod (key lookup failed)');
  process.exit(0);
}

const keys = await keysRes.json();
const anonKey = keys.find((k) => k.name === 'anon')?.api_key
  ?? keys.find((k) => k.name === 'default' && !k.api_key.includes('secret'))?.api_key;

if (!anonKey) {
  console.log('Could not find anon key — defaulting to prod');
  writeEnv(PROD_URL, PROD_ANON_KEY, 'prod (no anon key)');
  process.exit(0);
}

writeEnv(`https://${branchRef}.supabase.co`, anonKey, `preview branch: ${gitBranch}`);
