#!/usr/bin/env node
/**
 * Point .env.local at the Supabase preview branch for the current git branch.
 * Falls back to the persistent dev branch if no PR-specific branch exists.
 *
 * Usage: npm run env:local
 *
 * Requires SUPABASE_ACCESS_TOKEN env var (personal access token).
 * Set it in your shell profile or pass inline:
 *   SUPABASE_ACCESS_TOKEN=sbp_... npm run env:local
 */

import { execSync } from 'child_process';
import { writeFileSync, readFileSync } from 'fs';

const PROJECT_REF = 'mryuusvhdadbjpupzpol';
const VAPID_KEY = 'BE2z5xOQVkgl-GbMsaRi0nFmc8DpocUFkI_Li1vSHZSm-vE7H2EdYwpnQeTmSSSmtqXbCt4-wZC-Lk78US83ryc';

// Try to read access token from env or .env file
let accessToken = process.env.SUPABASE_ACCESS_TOKEN;
if (!accessToken) {
  try {
    const envFile = readFileSync('.env', 'utf8');
    const match = envFile.match(/SUPABASE_ACCESS_TOKEN=(.+)/);
    if (match) accessToken = match[1].trim();
  } catch {}
}

const gitBranch = execSync('git branch --show-current', { encoding: 'utf8' }).trim();
console.log(`Current branch: ${gitBranch}`);

function writeEnv(url, key, label) {
  const content = [
    `# Auto-generated by scripts/env-local.mjs`,
    `# ${label}`,
    `VITE_SUPABASE_URL=${url}`,
    `VITE_SUPABASE_ANON_KEY=${key}`,
    `VITE_VAPID_PUBLIC_KEY=${VAPID_KEY}`,
  ].join('\n') + '\n';
  writeFileSync('.env.local', content);
  console.log(`Wrote .env.local → ${url} (${label})`);
}

if (!accessToken) {
  console.error('No SUPABASE_ACCESS_TOKEN — set it in your shell or .env file');
  process.exit(1);
}

// Look for a preview branch matching the current git branch, fall back to dev
const lookupBranch = gitBranch === 'main' ? 'dev' : gitBranch;
console.log(`Looking for preview branch: ${lookupBranch}${gitBranch === 'main' ? ' (on main, using dev)' : ''}...`);

const res = await fetch(`https://api.supabase.com/v1/projects/${PROJECT_REF}/branches`, {
  headers: { Authorization: `Bearer ${accessToken}` },
});

if (!res.ok) {
  console.error(`Failed to list branches (${res.status})`);
  process.exit(1);
}

const branches = await res.json();
let branch = branches.find((b) => b.git_branch === lookupBranch);

// Fall back to dev branch if current branch has no preview
if (!branch && lookupBranch !== 'dev') {
  console.log(`No preview branch for "${lookupBranch}" — falling back to dev`);
  branch = branches.find((b) => b.git_branch === 'dev');
}

if (!branch) {
  console.error('No preview branch found (not even dev). Open a draft PR or create a dev branch.');
  process.exit(1);
}

const branchRef = branch.project_ref;
console.log(`Found preview branch: ${branchRef} (${branch.status})`);

// Get API keys
const keysRes = await fetch(`https://api.supabase.com/v1/projects/${branchRef}/api-keys`, {
  headers: { Authorization: `Bearer ${accessToken}` },
});

if (!keysRes.ok) {
  console.error(`Failed to get API keys (${keysRes.status})`);
  process.exit(1);
}

const keys = await keysRes.json();
const anonKey = keys.find((k) => k.name === 'anon')?.api_key
  ?? keys.find((k) => k.name === 'default' && !k.api_key.includes('secret'))?.api_key;

if (!anonKey) {
  console.error('Could not find anon key');
  process.exit(0);
}

writeEnv(`https://${branchRef}.supabase.co`, anonKey, `preview branch: ${gitBranch}`);
